apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: for-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      name: manual-kind
  storageClassName: standard
