apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-auto
  namespace: for-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard