# cluster creation setting up k8s env
# replace the paths with the actual PATH
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: ${path}/worker-1
        containerPath: ${container_path}
  - role: worker
    extraMounts:
      - hostPath: ${path}/worker-2
        containerPath: ${container_path}