apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-cluster
  namespace: for-rbac
spec:
  serviceAccountName: cluster-level
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]